In [1]:
import pandas as pd
import requests

# Empty list to store combined data
combined_data5 = []
# Iterate through pages
api_url = f'https://unstats.un.org/sdgapi/v1/sdg/Target/Data?target=5.5&areaCode=250&page=1&pageSize=1000'
# Fetch JSON data for each page
response = requests.get(api_url)
api_info = response.json()
# Append the "data" array from each page to the combined list
combined_data5.extend(api_info['data'])
# Add the combined "data" to the original JSON object
api_sum = combined_data5
#
df_api = pd.DataFrame(api_sum)

In [2]:
df_api.shape

(140, 21)

In [3]:
df_api

,goal,target,indicator,series,seriesDescription,seriesCount,geoAreaCode,geoAreaName,timePeriodStart,value,...,time_detail,timeCoverage,upperBound,lowerBound,basePeriod,source,geoInfoUrl,footnotes,attributes,dimensions
0,[5],[5.5],[5.5.1],SG_GEN_PARLN,Number of seats held by women in national parl...,5716,250,France,2000.0,63,...,None,None,None,None,None,"Inter-Parliamentary Union (IPU), the database ...",None,[Annual data as of 1 Feb of given year.],"{'Nature': 'C', 'Units': 'NUMBER'}","{'Sex': 'FEMALE', 'Reporting Type': 'G'}"
1,[5],[5.5],[5.5.1],SG_GEN_PARLN,Number of seats held by women in national parl...,5716,250,France,2001.0,63,...,None,None,None,None,None,"Inter-Parliamentary Union (IPU), the database ...",None,[Annual data as of 1 Feb of given year.],"{'Nature': 'C', 'Units': 'NUMBER'}","{'Sex': 'FEMALE', 'Reporting Type': 'G'}"
2,[5],[5.5],[5.5.1],SG_GEN_PARLN,Number of seats held by women in national parl...,5716,250,France,2002.0,63,...,None,None,None,None,None,"Inter-Parliamentary Union (IPU), the database ...",None,[Annual data as of 1 Feb of given year.],"{'Nature': 'C', 'Units': 'NUMBER'}","{'Sex': 'FEMALE', 'Reporting Type': 'G'}"
3,[5],[5.5],[5.5.1],SG_GEN_PARLN,Number of seats held by women in national parl...,5716,250,France,2003.0,70,...,None,None,None,None,None,"Inter-Parliamentary Union (IPU), the database ...",None,[Annual data as of 1 Feb of given year.],"{'Nature': 'C', 'Units': 'NUMBER'}","{'Sex': 'FEMALE', 'Reporting Type': 'G'}"
4,[5],[5.5],[5.5.1],SG_GEN_PARLN,Number of seats held by women in national parl...,5716,250,France,2004.0,70,...,None,None,None,None,None,"Inter-Parliamentary Union (IPU), the database ...",None,[Annual data as of 1 Feb of given year.],"{'Nature': 'C', 'Units': 'NUMBER'}","{'Sex': 'FEMALE', 'Reporting Type': 'G'}"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2018.0,34.38,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
136,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2019.0,34.3,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
137,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2020.0,34.95,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
138,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2021.0,36.77,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
139,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2022.0,39.39,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."

In [4]:
df_api.to_csv('dataset/raw_data/api_data5.5_raw.csv',index=False)

In [5]:
# Sélectionner les lignes où la colonne "series" est égale à "IC_GEN_MGTL_19ICLS" ou "IC_GEN_MGTN_19ICLS"
df_api_filtered = df_api[df_api['series'].isin(["IC_GEN_MGTL_19ICLS", "IC_GEN_MGTN_19ICLS"])].copy()

df_api_filtered

,goal,target,indicator,series,seriesDescription,seriesCount,geoAreaCode,geoAreaName,timePeriodStart,value,...,time_detail,timeCoverage,upperBound,lowerBound,basePeriod,source,geoInfoUrl,footnotes,attributes,dimensions
98,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2000.0,34.97,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: Eurostat special tabulation],"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
99,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2001.0,35.51,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: Eurostat special tabulation],"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
100,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2002.0,36.43,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: Eurostat special tabulation],"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
101,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2003.0,35.41,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: Eurostat special tabulation | Bre...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
102,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2004.0,35.89,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: Eurostat special tabulation],"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
103,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2005.0,37.6,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
104,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2006.0,37.88,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
105,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2007.0,37.83,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
106,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2008.0,38.5,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
107,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2009.0,38.09,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
108,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2010.0,38.54,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
109,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2011.0,39.34,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
110,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2012.0,39.32,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
111,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2013.0,36,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
112,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2014.0,32.74,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
113,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2015.0,31.66,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
114,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2016.0,32.91,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
115,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2017.0,33.44,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
116,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2018.0,34.44,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
117,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2019.0,34.67,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
118,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2020.0,35.53,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
119,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2021.0,37.79,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
120,[5],[5.5],[5.5.2],IC_GEN_MGTL_19ICLS,Proportion of women in managerial positions - ...,1252,250,France,2022.0,39.89,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
121,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2004.0,33.46,...,None,None,None,None,None,HIES - EU Statistics on Income and Living Cond...,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
122,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2005.0,36.37,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
123,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2006.0,37.01,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
124,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2007.0,36.46,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
125,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2008.0,36.79,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
126,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2009.0,37.37,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
127,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2010.0,38.59,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
128,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2011.0,39.13,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
129,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2012.0,39.2,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
130,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2013.0,35.58,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
131,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2014.0,32.03,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
132,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2015.0,30.93,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
133,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2016.0,31.07,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
134,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2017.0,32.64,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
135,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2018.0,34.38,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
136,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2019.0,34.3,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
137,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2020.0,34.95,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
138,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2021.0,36.77,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."
139,[5],[5.5],[5.5.2],IC_GEN_MGTN_19ICLS,Proportion of women in senior and middle manag...,958,250,France,2022.0,39.39,...,None,None,None,None,None,LFS - Employment Survey,None,[Repository: ILO-STATISTICS - Micro data proce...,"{'Nature': 'C', 'Units': 'PERCENT', 'Observati...","{'Age': '15+', 'Sex': 'FEMALE', 'Reporting Typ..."

In [6]:
# Créer un DataFrame avec les colonnes spécifiées
df_api_filtered = df_api_filtered.loc[:, ['seriesDescription', 'timePeriodStart', 'value']].copy()

# Afficher le DataFrame filtré
df_api_filtered

                                     seriesDescription  timePeriodStart  value
98   Proportion of women in managerial positions - ...           2000.0  34.97
99   Proportion of women in managerial positions - ...           2001.0  35.51
100  Proportion of women in managerial positions - ...           2002.0  36.43
101  Proportion of women in managerial positions - ...           2003.0  35.41
102  Proportion of women in managerial positions - ...           2004.0  35.89
103  Proportion of women in managerial positions - ...           2005.0   37.6
104  Proportion of women in managerial positions - ...           2006.0  37.88
105  Proportion of women in managerial positions - ...           2007.0  37.83
106  Proportion of women in managerial positions - ...           2008.0   38.5
107  Proportion of women in managerial positions - ...           2009.0  38.09
108  Proportion of women in managerial positions - ...           2010.0  38.54
109  Proportion of women in managerial positions - ...           2011.0  39.34
110  Proportion of women in managerial positions - ...           2012.0  39.32
111  Proportion of women in managerial positions - ...           2013.0     36
112  Proportion of women in managerial positions - ...           2014.0  32.74
113  Proportion of women in managerial positions - ...           2015.0  31.66
114  Proportion of women in managerial positions - ...           2016.0  32.91
115  Proportion of women in managerial positions - ...           2017.0  33.44
116  Proportion of women in managerial positions - ...           2018.0  34.44
117  Proportion of women in managerial positions - ...           2019.0  34.67
118  Proportion of women in managerial positions - ...           2020.0  35.53
119  Proportion of women in managerial positions - ...           2021.0  37.79
120  Proportion of women in managerial positions - ...           2022.0  39.89
121  Proportion of women in senior and middle manag...           2004.0  33.46
122  Proportion of women in senior and middle manag...           2005.0  36.37
123  Proportion of women in senior and middle manag...           2006.0  37.01
124  Proportion of women in senior and middle manag...           2007.0  36.46
125  Proportion of women in senior and middle manag...           2008.0  36.79
126  Proportion of women in senior and middle manag...           2009.0  37.37
127  Proportion of women in senior and middle manag...           2010.0  38.59
128  Proportion of women in senior and middle manag...           2011.0  39.13
129  Proportion of women in senior and middle manag...           2012.0   39.2
130  Proportion of women in senior and middle manag...           2013.0  35.58
131  Proportion of women in senior and middle manag...           2014.0  32.03
132  Proportion of women in senior and middle manag...           2015.0  30.93
133  Proportion of women in senior and middle manag...           2016.0  31.07
134  Proportion of women in senior and middle manag...           2017.0  32.64
135  Proportion of women in senior and middle manag...           2018.0  34.38
136  Proportion of women in senior and middle manag...           2019.0   34.3
137  Proportion of women in senior and middle manag...           2020.0  34.95
138  Proportion of women in senior and middle manag...           2021.0  36.77
139  Proportion of women in senior and middle manag...           2022.0  39.39

In [7]:
df_api_filtered.columns

Index(['seriesDescription', 'timePeriodStart', 'value'], dtype='object')

In [8]:
# Renommer la colonne 'timePeriodStart' en 'time_period'
df_api_filtered.rename(columns={'timePeriodStart': 'time_period'}, inplace=True)

# Convertir les valeurs de la colonne 'time_period' en entiers
df_api_filtered['time_period'] = df_api_filtered['time_period'].astype(int)

df_api_filtered

                                     seriesDescription  time_period  value
98   Proportion of women in managerial positions - ...         2000  34.97
99   Proportion of women in managerial positions - ...         2001  35.51
100  Proportion of women in managerial positions - ...         2002  36.43
101  Proportion of women in managerial positions - ...         2003  35.41
102  Proportion of women in managerial positions - ...         2004  35.89
103  Proportion of women in managerial positions - ...         2005   37.6
104  Proportion of women in managerial positions - ...         2006  37.88
105  Proportion of women in managerial positions - ...         2007  37.83
106  Proportion of women in managerial positions - ...         2008   38.5
107  Proportion of women in managerial positions - ...         2009  38.09
108  Proportion of women in managerial positions - ...         2010  38.54
109  Proportion of women in managerial positions - ...         2011  39.34
110  Proportion of women in managerial positions - ...         2012  39.32
111  Proportion of women in managerial positions - ...         2013     36
112  Proportion of women in managerial positions - ...         2014  32.74
113  Proportion of women in managerial positions - ...         2015  31.66
114  Proportion of women in managerial positions - ...         2016  32.91
115  Proportion of women in managerial positions - ...         2017  33.44
116  Proportion of women in managerial positions - ...         2018  34.44
117  Proportion of women in managerial positions - ...         2019  34.67
118  Proportion of women in managerial positions - ...         2020  35.53
119  Proportion of women in managerial positions - ...         2021  37.79
120  Proportion of women in managerial positions - ...         2022  39.89
121  Proportion of women in senior and middle manag...         2004  33.46
122  Proportion of women in senior and middle manag...         2005  36.37
123  Proportion of women in senior and middle manag...         2006  37.01
124  Proportion of women in senior and middle manag...         2007  36.46
125  Proportion of women in senior and middle manag...         2008  36.79
126  Proportion of women in senior and middle manag...         2009  37.37
127  Proportion of women in senior and middle manag...         2010  38.59
128  Proportion of women in senior and middle manag...         2011  39.13
129  Proportion of women in senior and middle manag...         2012   39.2
130  Proportion of women in senior and middle manag...         2013  35.58
131  Proportion of women in senior and middle manag...         2014  32.03
132  Proportion of women in senior and middle manag...         2015  30.93
133  Proportion of women in senior and middle manag...         2016  31.07
134  Proportion of women in senior and middle manag...         2017  32.64
135  Proportion of women in senior and middle manag...         2018  34.38
136  Proportion of women in senior and middle manag...         2019   34.3
137  Proportion of women in senior and middle manag...         2020  34.95
138  Proportion of women in senior and middle manag...         2021  36.77
139  Proportion of women in senior and middle manag...         2022  39.39

In [9]:
df_api_filtered.rename(columns={'seriesDescription': 'serie_description'}, inplace=True)

In [10]:
df_api_pivot = df_api_filtered.pivot(index='time_period', columns='serie_description', values='value')
df_api_pivot

serie_description,Proportion of women in managerial positions - 19th ICLS (%),Proportion of women in senior and middle management positions - 19th ICLS (%)
time_period,,
2000,34.97,NaN
2001,35.51,NaN
2002,36.43,NaN
2003,35.41,NaN
2004,35.89,33.46
2005,37.6,36.37
2006,37.88,37.01
2007,37.83,36.46
2008,38.5,36.79
2009,38.09,37.37
2010,38.54,38.59
2011,39.34,39.13
2012,39.32,39.2
2013,36,35.58
2014,32.74,32.03
2015,31.66,30.93
2016,32.91,31.07
2017,33.44,32.64
2018,34.44,34.38
2019,34.67,34.3
2020,35.53,34.95
2021,37.79,36.77
2022,39.89,39.39

In [11]:
df_api_pivot.columns

Index(['Proportion of women in managerial positions - 19th ICLS (%)', 'Proportion of women in senior and middle management positions - 19th ICLS (%)'], dtype='object', name='serie_description')

In [12]:
df_api_pivot.rename(columns={
    'Proportion of women in managerial positions - 19th ICLS (%)': '%_women_in_managerial_positions',
    'Proportion of women in senior and middle management positions - 19th ICLS (%)': '%_women_in_senior_middle_management'
}, inplace=True)

In [13]:
df_api_pivot.dropna(inplace=True)

In [14]:
df_api_pivot

serie_description,%_women_in_managerial_positions,%_women_in_senior_middle_management
time_period,,
2004,35.89,33.46
2005,37.6,36.37
2006,37.88,37.01
2007,37.83,36.46
2008,38.5,36.79
2009,38.09,37.37
2010,38.54,38.59
2011,39.34,39.13
2012,39.32,39.2
2013,36,35.58
2014,32.74,32.03
2015,31.66,30.93
2016,32.91,31.07
2017,33.44,32.64
2018,34.44,34.38
2019,34.67,34.3
2020,35.53,34.95
2021,37.79,36.77
2022,39.89,39.39

In [15]:
# Convertir les colonnes en types numériques
df_api_pivot['%_women_in_managerial_positions'] = pd.to_numeric(df_api_pivot['%_women_in_managerial_positions'], errors='coerce')
df_api_pivot['%_women_in_senior_middle_management'] = pd.to_numeric(df_api_pivot['%_women_in_senior_middle_management'], errors='coerce')

# Calculer la différence entre les deux colonnes et l'assigner à une nouvelle colonne
df_api_pivot['%_women_in_junior_management'] = df_api_pivot['%_women_in_managerial_positions'] - df_api_pivot['%_women_in_senior_middle_management']

df_api_pivot

serie_description,%_women_in_managerial_positions,%_women_in_senior_middle_management,%_women_in_junior_management
time_period,,,
2004,35.89,33.46,2.43
2005,37.60,36.37,1.23
2006,37.88,37.01,0.87
2007,37.83,36.46,1.37
2008,38.50,36.79,1.71
2009,38.09,37.37,0.72
2010,38.54,38.59,-0.05
2011,39.34,39.13,0.21
2012,39.32,39.20,0.12
2013,36.00,35.58,0.42
2014,32.74,32.03,0.71
2015,31.66,30.93,0.73
2016,32.91,31.07,1.84
2017,33.44,32.64,0.80
2018,34.44,34.38,0.06
2019,34.67,34.30,0.37
2020,35.53,34.95,0.58
2021,37.79,36.77,1.02
2022,39.89,39.39,0.50

In [16]:
df_api_pivot.shape

(19, 3)

In [17]:
df_api_pivot.dtypes

serie_description
%_women_in_managerial_positions        float64
%_women_in_senior_middle_management    float64
%_women_in_junior_management           float64
dtype: object

In [18]:

df_api_pivot['%_women_in_managerial_positions'] = df_api_pivot['%_women_in_managerial_positions'].astype(float)
df_api_pivot['%_women_in_senior_middle_management'] = df_api_pivot['%_women_in_senior_middle_management'].astype(float)


df_api_pivot['%_women_in_managerial_positions'] = df_api_pivot['%_women_in_managerial_positions'].round(2)
df_api_pivot['%_women_in_senior_middle_management'] = df_api_pivot['%_women_in_senior_middle_management'].round(2)

In [19]:
df_api_pivot

serie_description,%_women_in_managerial_positions,%_women_in_senior_middle_management,%_women_in_junior_management
time_period,,,
2004,35.89,33.46,2.43
2005,37.60,36.37,1.23
2006,37.88,37.01,0.87
2007,37.83,36.46,1.37
2008,38.50,36.79,1.71
2009,38.09,37.37,0.72
2010,38.54,38.59,-0.05
2011,39.34,39.13,0.21
2012,39.32,39.20,0.12
2013,36.00,35.58,0.42
2014,32.74,32.03,0.71
2015,31.66,30.93,0.73
2016,32.91,31.07,1.84
2017,33.44,32.64,0.80
2018,34.44,34.38,0.06
2019,34.67,34.30,0.37
2020,35.53,34.95,0.58
2021,37.79,36.77,1.02
2022,39.89,39.39,0.50

In [20]:
df_api_pivot.to_csv('dataset/raw_data/data_from_api.csv', index=False)

In [21]:
df = pd.read_csv('dataset/raw_data/data_from_api.csv')
df

,%_women_in_managerial_positions,%_women_in_senior_middle_management,%_women_in_junior_management
0,35.89,33.46,2.43
1,37.60,36.37,1.23
2,37.88,37.01,0.87
3,37.83,36.46,1.37
4,38.50,36.79,1.71
5,38.09,37.37,0.72
6,38.54,38.59,-0.05
7,39.34,39.13,0.21
8,39.32,39.20,0.12
9,36.00,35.58,0.42
10,32.74,32.03,0.71
11,31.66,30.93,0.73
12,32.91,31.07,1.84
13,33.44,32.64,0.80
14,34.44,34.38,0.06
15,34.67,34.30,0.37
16,35.53,34.95,0.58
17,37.79,36.77,1.02
18,39.89,39.39,0.50

In [22]:
df.columns

Index(['%_women_in_managerial_positions',
       '%_women_in_senior_middle_management', '%_women_in_junior_management'],
      dtype='object')

In [23]:
years = list(range(2004, 2023))

time_periods = pd.DataFrame({'time_period': years})

df = pd.concat([time_periods, df], axis=1)
df

,time_period,%_women_in_managerial_positions,%_women_in_senior_middle_management,%_women_in_junior_management
0,2004,35.89,33.46,2.43
1,2005,37.60,36.37,1.23
2,2006,37.88,37.01,0.87
3,2007,37.83,36.46,1.37
4,2008,38.50,36.79,1.71
5,2009,38.09,37.37,0.72
6,2010,38.54,38.59,-0.05
7,2011,39.34,39.13,0.21
8,2012,39.32,39.20,0.12
9,2013,36.00,35.58,0.42
10,2014,32.74,32.03,0.71
11,2015,31.66,30.93,0.73
12,2016,32.91,31.07,1.84
13,2017,33.44,32.64,0.80
14,2018,34.44,34.38,0.06
15,2019,34.67,34.30,0.37
16,2020,35.53,34.95,0.58
17,2021,37.79,36.77,1.02
18,2022,39.89,39.39,0.50

In [25]:
df.to_csv('dataset/clean_data/data_from_api_clean.csv', index=False)

In [27]:
woman_managerial_position = df.copy()

In [29]:
woman_managerial_position.columns

Index(['time_period', '%_women_in_managerial_positions',
       '%_women_in_senior_middle_management', '%_women_in_junior_management'],
      dtype='object')